services:
  main-rproxy:
    image: caddy:2
    command: caddy reverse-proxy --from whoami.docker.localhost:80 --to whoami:80
    ports:
      - 80:80
    networks:
      - web
      - private

  whoami:
    image: traefik/whoami
    networks:
      - private

  jailed-worker:
    image: nicolaka/netshoot
    command: sleep 6000
    init: true
    networks:
      - private

networks:
  web:
    name: web
  private:
    name: private
    internal: true
